stages:
  - build

build_images:
  stage: build
  image: docker:20.10.16

  services:
    - docker:20.10.16-dind
  
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  
  before_script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASS
  
  script:
    - docker build app/. -t fabiosilva07/projeto-php-app:1.0
    - docker push fabiosilva07/projeto-php-app:1.0
    - docker build database/. -t fabiosilva07/projeto-php-db:2.0
    - docker push fabiosilva07/projeto-php-db:2.0