apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-data
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  nfs:
    path: /data/mysql
    server: 192.168.0.5

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-data
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  volumeName: db-data
  resources:
    requests:
      storage: 2Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-app
  labels:
    app: php-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: php-app
  template:
    metadata:
      labels:
        app: php-app
    spec:
      containers:
      - name: php-app
        image: fabiosilva07/projeto-php-app:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: DB_USER
          value: root
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: dbpass
              key: ROOT_PASSWORD
        - name: DATABASE
          valueFrom:
            secretKeyRef:
              name: dbpass
              key: MYSQL_DATABASE

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-db
spec:
  selector:
    matchLabels:
      app: app-db
  template:
    metadata:
      labels:
        app: app-db
    spec:
      volumes:
      - name: db-data
        persistentVolumeClaim:
          claimName: db-data
      containers:
      - name: app-db
        image: fabiosilva07/projeto-php-db:2.0
        imagePullPolicy: Always
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: dbpass
              key: ROOT_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: dbpass
              key: MYSQL_DATABASE
        volumeMounts:
        - name: db-data
          mountPath: /var/lib/mysql/