apiVersion: v1
kind: Service
metadata:
  name: mysql-connection
spec:
  ports:
  - port: 3306
  selector:
    app: app-db
  clusterIP: None

---

apiVersion: v1
kind: Service
metadata:
  name: app-php-load
spec:
  selector:
    app: php-app
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer