machines = {
  "master" => {"memory" => "2048", "cpu" => "1", "ip" => "192.168.0.3", "image" => "bento/ubuntu-22.04"},
  "node01" => {"memory" => "512", "cpu" => "1", "ip" => "192.168.0.4", "image" => "bento/ubuntu-22.04"},
  "node02" => {"memory" => "512", "cpu" => "1", "ip" => "192.168.0.5", "image" => "bento/ubuntu-22.04"}
}

Vagrant.configure("2") do |config|
  machines.each do |name, conf|
    config.vm.define "#{name}" do |machine|
      machine.vm.box = "#{conf["image"]}"
      machine.vm.hostname = "#{name}"
      machine.vm.network "public_network", ip: "#{conf["ip"]}"
      machine.vm.provider "virtualbox" do |vb|
        vb.name = "#{name}"
        vb.memory = conf["memory"]
        vb.cpus = conf["cpu"]
        
      end
      if "#{name}" == "master"
        machine.vm.provision "shell", path: "instalar-docker-manager.sh"
        machine.vm.provision "shell", path: "instalar-app.sh" 
      else
        machine.vm.provision "shell", path: "instalar-docker-worker.sh"
      end
    end
  end
end